---

- hosts: all
  become: true
  pre_tasks:
    - name: Check for grub config
      stat:
        path: "/etc/default/grub"
      register: __grub_conf

    - name: Look for grub.cfg
      find:
        paths: /boot/efi/EFI
        patterns: 'grub.cfg'
        recurse: true
      register: __grub_search

    - name: Set grub.cfg path
      set_fact:
        grub_cfg_path: "{{ __grub_search.files[0].path }}"
      when: __grub_search.matched > 0

  tasks:
    - name: Disable grub timeout
      lineinfile:
        dest: "/etc/default/grub"
        regexp: '^GRUB_TIMEOUT'
        line: "GRUB_TIMEOUT=0"
        state: present
      when: __grub_conf.stat.exists
      notify: regenerate grub

    - name: Install root keys
      authorized_key:
        user: root
        state: present
        key: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOg9fiCqlSj0Xm/+rA02ecxnDYecKEnhYol6WUrM29UA andrei@desktop
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDCHMjI/tkb21/PtXRfj8VBsqGJn9TkP0+XDkw7LZ+5x andrei@laptop

    - name: Set more secure root password
      user:
        name: root
        password: '$6$UEcjS6FuN34m0LNh$keSth27mGIKRgk4goS.SZJRJX4WlP71wRf8hsHVlRbnhA1NC3QRSPanqyUWC26SDAvZyyiaE2n1dMUSVe6VcJ1'

  handlers:
    - name: regenerate grub
      command: "grub2-mkconfig -o {{ grub_cfg_path }}"
      when: "grub_cfg_path is defined"
