---

- name: Localhost actions
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Clear host SSH keys
      delegate_to: localhost
      ansible.builtin.command: "ssh-keygen -R {{ ansible_host }}"
      ignore_errors: true

- name: Basic provisioning
  hosts: all
  become: true
  vars:
    dnf_automatic_timer_enabled: true
    dnf_automatic_upgrade_type: "security"
    dnf_automatic_apply_updates: true
    dnf_automatic_download_updates: true
    unattended_remove_unused_dependencies: true
    unattended_remove_new_unused_dependencies: true
    unattended_automatic_reboot: false
  pre_tasks:
    - name: Check for grub config
      ansible.builtin.stat:
        path: "/etc/default/grub"
      register: __grub_conf

    - name: Look for grub.cfg
      ansible.builtin.find:
        paths: /boot/efi/EFI
        patterns: 'grub.cfg'
        recurse: true
      register: __grub_search

    - name: Set grub.cfg path
      ansible.builtin.set_fact:
        grub_cfg_path: "{{ __grub_search.files[0].path }}"
      when: __grub_search.matched > 0

  roles:
    - role: cosandr.unattended-upgrades
      when: ansible_os_family == 'Debian'

    - role: cosandr.dnf_automatic
      when: ansible_os_family == 'RedHat'

    - role: cosandr.epel
      when:
        - "'intelgpu' in source_name"
        - ansible_os_family == 'RedHat'

    - role: cosandr.firewall_config
      vars:
        firewall_rules: "{{ family_rules.get(ansible_os_family, []) }}"
        family_rules:
          Debian:
            - port: 22

  tasks:
    - name: Update all packages (RedHat)  # noqa package-latest
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Update all packages (Debian)  # noqa package-latest
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install some packages
      ansible.builtin.package:
        name: "{{ common_packages + family_packages.get(ansible_os_family, []) }}"
        state: present
      vars:
        common_packages:
          - bash-completion
        family_packages:
          RedHat:
            - glibc-locale-source
            - glibc-langpack-en

    - name: Install grow-rootfs script
      ansible.builtin.copy:
        src: grow-rootfs.sh
        dest: /usr/bin/grow-rootfs
        owner: root
        group: root
        mode: 0755

    - name: Install grow-rootfs service
      ansible.builtin.copy:
        src: grow-rootfs.service
        dest: "/etc/systemd/system/grow-rootfs.service"
        owner: root
        group: root
        mode: 0644
      notify: Enable grow-rootfs

    - name: Install template-first-boot script
      ansible.builtin.copy:
        src: template-first-boot.sh
        dest: /usr/bin/template-first-boot
        owner: root
        group: root
        mode: 0755

    - name: Install template-first-boot service
      ansible.builtin.copy:
        src: template-first-boot.service
        dest: "/etc/systemd/system/template-first-boot.service"
        owner: root
        group: root
        mode: 0644
      notify: Enable template-first-boot

    - name: Reduce grub timeout
      ansible.builtin.lineinfile:
        dest: "/etc/default/grub"
        regexp: '^GRUB_TIMEOUT'
        line: "GRUB_TIMEOUT=2"
        state: present
      when: __grub_conf.stat.exists
      notify: Regenerate grub

    - name: Disable virtual terminals allocation by logind
      ansible.builtin.lineinfile:
        dest: '/etc/systemd/logind.conf'
        regexp: '^#?NAutoVTs='
        line: 'NAutoVTs=0'
        state: present

    - name: Install root keys
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'authorized_keys') }}"

    - name: Set more secure root password
      ansible.builtin.user:
        name: root
        password: '$6$UEcjS6FuN34m0LNh$keSth27mGIKRgk4goS.SZJRJX4WlP71wRf8hsHVlRbnhA1NC3QRSPanqyUWC26SDAvZyyiaE2n1dMUSVe6VcJ1'

    # Cannot use -*firmware in kickstart because kernel-core recommends linux-firmware causing Anaconda to fail.
    # Keep linux-firmware for GPU builds, removing it causes (appears to work however)
    # Direct firmware load for i915/kbl_dmc_ver1_04.bin failed with error -2
    # [drm] Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin. Disabling runtime power management.
    # [drm] DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
    - name: Remove firmwares
      ansible.builtin.dnf:
        name: "*firmware"
        state: absent
      when:
        - ansible_os_family == 'RedHat'
        - "'intelgpu' not in source_name"

    - name: Setup Intel GPUs
      when:
        - "'intelgpu' in source_name"
        # TODO: Debian support
        - ansible_os_family == 'RedHat'
      block:
        - name: Install RPMFusion (Fedora)
          ansible.builtin.dnf:
            state: present
            name:
              - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
              - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
          when: ansible_distribution == 'Fedora'

        - name: Configure openh264 library
          ansible.builtin.command: dnf config-manager --enable fedora-cisco-openh264
          when: ansible_distribution == 'Fedora'

        - name: Install RPMFusion (RHEL)
          ansible.builtin.dnf:
            state: present
            disable_gpg_check: true
            name:
              - "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
              - "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
          when: ansible_distribution != 'Fedora'

        - name: Install intel-media-driver
          ansible.builtin.dnf:
            name: intel-media-driver
            state: present

  handlers:
    - name: Enable grow-rootfs
      ansible.builtin.systemd:
        daemon_reload: true
        name: grow-rootfs.service
        enabled: true

    - name: Enable template-first-boot
      ansible.builtin.systemd:
        daemon_reload: true
        name: template-first-boot.service
        enabled: true

    - name: Regenerate grub (RedHat)
      listen: Regenerate grub
      ansible.builtin.command: "grub2-mkconfig -o {{ grub_cfg_path }}"
      when:
        - grub_cfg_path is defined
        - ansible_os_family == 'RedHat'

    - name: Regenerate grub (Debian)
      listen: Regenerate grub
      ansible.builtin.command: "update-grub"
      when: ansible_os_family == 'Debian'
