---

- hosts: all
  become: true
  vars:
    dnf_automatic_timer_enabled: true
    dnf_automatic_upgrade_type: "security"
    dnf_automatic_apply_updates: true
    dnf_automatic_download_updates: true
    unattended_remove_unused_dependencies: true
    unattended_remove_new_unused_dependencies: true
    unattended_automatic_reboot: false
  pre_tasks:
    - name: Check for grub config
      stat:
        path: "/etc/default/grub"
      register: __grub_conf

    - name: Look for grub.cfg
      find:
        paths: /boot/efi/EFI
        patterns: 'grub.cfg'
        recurse: true
      register: __grub_search

    - name: Set grub.cfg path
      set_fact:
        grub_cfg_path: "{{ __grub_search.files[0].path }}"
      when: __grub_search.matched > 0

  roles:
    - role: jnv.unattended-upgrades
      when: ansible_os_family == 'Debian'

    - role: cosandr.dnf_automatic
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Update all packages (RedHat)
      dnf:
        name: '*'
        state: latest
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Update all packages (Debian)
      apt:
        name: "*"
        state: latest
        update_cache: true
        autoclean: true
        autoremove: true
      when: ansible_os_family == 'Debian'

    - name: Install some packages
      package:
        name:
          - bash-completion
        state: present

    - name: Install grow-rootfs script
      copy:
        dest: /usr/bin/grow-rootfs
        owner: root
        group: root
        mode: 0755
        content: |
          #!/bin/bash
          set -euo pipefail

          if ! fdisk -l /dev/sda 2>&1 >/dev/null | grep -q 'size mismatch'; then
            echo "No mismatch detected"
            exit 0
          fi

          growpart /dev/sda 3
          resize2fs /dev/sda3
          systemctl disable grow-rootfs.service

    - name: Install grow-rootfs service
      copy:
        dest: "/etc/systemd/system/grow-rootfs.service"
        owner: root
        group: root
        mode: 0644
        content: |
          [Unit]
          Description=Resize rootfs on boot

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/grow-rootfs

          [Install]
          WantedBy=local-fs.target
      notify: enable grow-rootfs

    - name: Disable grub timeout
      lineinfile:
        dest: "/etc/default/grub"
        regexp: '^GRUB_TIMEOUT'
        line: "GRUB_TIMEOUT=0"
        state: present
      when: __grub_conf.stat.exists
      notify: regenerate grub

    - name: Install root keys
      authorized_key:
        user: root
        state: present
        key: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOg9fiCqlSj0Xm/+rA02ecxnDYecKEnhYol6WUrM29UA andrei@desktop
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDCHMjI/tkb21/PtXRfj8VBsqGJn9TkP0+XDkw7LZ+5x andrei@laptop

    - name: Set more secure root password
      user:
        name: root
        password: '$6$UEcjS6FuN34m0LNh$keSth27mGIKRgk4goS.SZJRJX4WlP71wRf8hsHVlRbnhA1NC3QRSPanqyUWC26SDAvZyyiaE2n1dMUSVe6VcJ1'

  handlers:
    - name: enable grow-rootfs
      systemd:
        daemon_reload: true
        name: grow-rootfs.service
        enabled: true

    - name: regenerate grub
      command: "grub2-mkconfig -o {{ grub_cfg_path }}"
      when: "grub_cfg_path is defined"
