---

- hosts: all
  become: true
  pre_tasks:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/docker/compose/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5
      check_mode: false

    - name: "Set compose version to {{ _latest_release.json.tag_name }}"
      set_fact:
        docker_compose_version: "{{ _latest_release.json.tag_name }}"
  roles:
    - role: geerlingguy.docker
